name: Maven构建

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-files:
    name: 检查仓库文件
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.check-changed-files.outputs.all_changed_and_modified_files }}

    steps:
      - name: 检出仓库内容
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 检查文件改动情况
        id: check-changed-files
        uses: tj-actions/changed-files@v11.4
        with:
          since_last_remote_commit: 'true'

      - name: 输出更改文件列表
        run: echo ${{ steps.check-changed-files.outputs.all_changed_and_modified_files }}

  build-BDLCompiler:
    name: 构建bdl编译器
    runs-on: ubuntu-latest
    needs: check-files
    if: contains(needs.check-files.outputs.changed-files, 'BDLCompiler/') || (github.event_name == 'push' && contains(github.event.commits[0].message, '发布新版本'))

    steps:
      - name: 检出仓库内容
        uses: actions/checkout@v2

      - name: 缓存Maven依赖项
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-BDLCompiler
          restore-keys: |
            ${{ runner.os }}-maven-BDLCompiler

      - uses: actions/setup-java@v2
        name: 配置jdk8
        with:
          distribution: 'adopt-hotspot'
          java-version: '8'

      - name: Maven构建
        run: mvn -B package --file pom.xml --pl BDLCompiler

      - name: 上传bdl编译器
        uses: actions/upload-artifact@v2
        with:
          name: BDLCompiler
          path: BDLCompiler/target/BDLCompiler*.jar

      - name: 上传bdl编译器运行库
        uses: actions/upload-artifact@v2
        with:
          name: BDLCompilerLib
          path:
            BDLCompiler/target/libs/*.jar

  build-BDLauncher:
    name: 编译启动器
    runs-on: windows-latest
    needs: check-files
    if: contains(needs.check-files.outputs.changed-files, 'BDLauncher/') || (github.event_name == 'push' && contains(github.event.commits[0].message, '发布新版本'))

    steps:
      - name: 检出仓库内容
        uses: actions/checkout@v2

      - name: 缓存Maven依赖项
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-BDLauncher
          restore-keys: |
            ${{ runner.os }}-maven-BDLauncher

      - uses: actions/setup-java@v2
        name: 配置jdk8
        with:
          distribution: 'adopt-hotspot'
          java-version: '8'

      - name: 配置rust工具链
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-pc-windows-msvc
          override: true

      - name: Maven构建
        run: mvn -B package --file pom.xml --pl BDLauncher

      - name: 上传可执行文件
        uses: actions/upload-artifact@v2
        with:
          name: Launcher-Windows
          path: BDLauncher/target/release/bdl.exe

  release:
    name: 发布新版本
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.event.commits[0].message, '发布新版本')
    needs:
      - build-BDLCompiler
      - build-BDLauncher
    steps:
      - uses: actions/checkout@v2
        name: 检出仓库内容

      - uses: actions/download-artifact@v2
        name: 下载所有构件
        with:
          path: artifacts/

      - name: 压缩构件
        run: bash .github/scripts/zip.sh artifacts

      - uses: zoexx/github-action-json-file-properties@release
        name: 获取发布信息
        id: get-release-info
        with:
          file_path: '.github/release-info.json'

      - uses: ncipollo/release-action@v1
        name: 发布新版本
        with:
          artifacts: "artifacts/zipped/*.zip"
          tag: ${{ steps.get-release-info.outputs.version }}
          prerelease: ${{ contains(steps.get-release-info.outputs.version, 'beta') }}
          bodyFile: ${{ steps.get-release-info.outputs.body_path }}
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: master
          allowUpdates: true
